# Generated by Django 4.0.4 on 2022-04-14 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='datetime',
        ),
    ]
